"""
Channel-specific response formatters.

Ensures responses match the expectations for each channel (email, whatsapp, web_form).
"""

from typing import Optional
from dataclasses import dataclass
from datetime import datetime
from enum import Enum

from .prompts import CUSTOMER_SUCCESS_SYSTEM_PROMPT


class Channel(str, Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


@dataclass
class FormattingContext:
    customer_name: Optional[str] = None
    ticket_id: Optional[str] = None
    subject: Optional[str] = None
    channel: Channel = Channel.EMAIL
    is_enterprise: bool = False


def format_response(response_text: str, context: FormattingContext) -> str:
    """Format a response for the appropriate channel."""
    formatter = CHANNEL_FORMATTERS[context.channel]
    return formatter(response_text, context)


def _format_email(response_text: str, context: FormattingContext) -> str:
    """Format response for email (formal, detailed)."""
    greeting = "Dear Customer,"
    if context.customer_name:
        greeting = f"Dear {context.customer_name},"

    has_ticket_id = context.ticket_id is not None
    ticket_ref = f"\n\n---\nTicket Reference: {context.ticket_id}\n"

    footer = """\n\nThis response was generated by our AI assistant. If you need additional assistance or believe the information is incorrect, please reply to this email or call us at 1-800-FLOWSYNC.
\nBest regards,
TechCorp AI Support Team"""

    full_response = f"""{greeting}

Thank you for contacting TechCorp Support.

{response_text}

If you have any further questions, please don't hesitate to reach out."""

    if has_ticket_id:
        full_response += ticket_ref

    full_response += footer

    # Limit to max 3000 chars (~500 words)
    if len(full_response) > 3000:
        # Trim to length that maintains structure
        cutoff = full_response[:2900]
        full_response = cutoff.rsplit('\n', 1)[0] + "...\n\n[Response truncated for email length]"

    return full_response


def _format_whatsapp(response_text: str, context: FormattingContext) -> str:
    """Format response for WhatsApp (concise, conversational)."""
    # WhatsApp max is 1600 chars, but prefer under 300 for best UX
    if len(response_text) > 300:
        # Truncate but preserve first message
        response_text = response_text[:280] + "..."

    # No formal greeting, but can be friendly
    lines = []
    if context.customer_name:
        lines.append(f"Hi {context.customer_name},")
    else:
        lines.append("Hi there,")

    lines.append("")
    lines.append(response_text)
    lines.append("")
    lines.append("If this helps, let me know! Reply with more questions or type 'human' to speak with our team.")

    full_response = "\n".join(lines)

    # Max 1600 chars per message, but we try to keep under 300
    if len(full_response) > 1600:
        # Very rare - would need to split into multiple messages
        return full_response[:1597] + "..."

    return full_response


def _format_web_form(response_text: str, context: FormattingContext) -> str:
    """Format response for Web Form (semi-formal, embedded UI)."""
    greeting = "Hello,"
    if context.customer_name:
        greeting = f"Hello {context.customer_name},"

    footer = """

---
Need more help? Reply to this message or visit our [support portal](https://help.flowsync.com).

This is an automated response. If you're not satisfied or need immediate assistance, please let us know!"""

    full_response = f"""{greeting}

Thank you for your support request.

{response_text}

We typically respond within minutes. Is there anything else we can help with?""" + footer

    # Keep under 1800 chars
    if len(full_response) > 1800:
        cutoff = full_response[:1700]
        full_response = cutoff.rsplit('\n', 1)[0] + footer

    return full_response


CHANNEL_FORMATTERS = {
    Channel.EMAIL: _format_email,
    Channel.WHATSAPP: _format_whatsapp,
    Channel.WEB_FORM: _format_web_form,
}


def format_escalation_message(reason: str, context: FormattingContext) -> str:
    """Generate escalation message to customer."""
    if context.channel == Channel.WHATSAPP:
        return "I'm escalating this to a human specialist. They'll get back to you within 2 hours. Thanks for your patience!"
    elif context.channel == Channel.EMAIL:
        return f"""Dear Customer,

I'm connecting you with one of our specialist support agents who will be able to provide more detailed assistance regarding: {reason}.

You can expect a response within 2 hours via email.

Thank you for your patience.

Best regards,
TechCorp AI Support"""
    else:
        return f"""Hello,

Thank you for your request. I'm transferring this to a human support agent who can better assist you.

This typically happens within 2 hours. You'll receive an email notification when they respond.

- TechCorp Support AI"""
